const TripTbl = [
         {
            "ID": "1",
            "Trip": "Murray1",
            "StartDate": "2009-01-10T00:00:00",
            "Duration": "1",
            "Place": "Lake Murray",
            "Photos": "F:\\D_Drive\\FishProject\\images\\bass-1024.jpg",
            "Notes": "blah",
            "Anglers": "Willie",
            "GPS1": "N23.234",
            "GPS2": "W34.567",
            "ImgCaption": "guess the fish size and win!",
            "CatchTbl": [
               {
                  "ID": "1",
                  "Species": "LMB",
                  "CatchDate": "2010-04-26T00:00:00",
                  "Trip": "Murray1",
                  "Location": "Under wires",
                  "Angler": "Willie",
                  "Quantity": "1",
                  "Weight": "5",
                  "Length": "24",
                  "Girth": "26",
                  "FightTime": "4",
                  "Outcome": "Released",
                  "Style": "Texas",
                  "Bait": "Senko",
                  "BaitColor": "green",
                  "Notes": "blah blah",
                  "AirTemp": "69",
                  "WindDirection": "s",
                  "Wind": "strong",
                  "SkyCondition": "cloudy",
                  "LunarPhase": "Full",
                  "Pressure": "34",
                  "Barometer": "45",
                  "WaterTemp": "65",
                  "WaterDepth": "20",
                  "WaterPh": "2",
                  "Current": "2",
                  "Bottom": "rocky",
                  "WaterColor": "clear",
                  "Tide": "high",
                  "WaterLevel": "high",
                  "Seas": "rough",
                  "Rod": "Shimano",
                  "Reel": "Shimano",
                  "HookSize": "4",
                  "HookType": "Circle",
                  "SinkerWeight": "2.25",
                  "SinkerStyle": "split shot",
                  "LineTest": "10",
                  "LineStyle": "Mono",
                  "LineColor": "Clear",
                  "ImgCaption": "Chuckawalla Lizard"
               },
               {
                  "ID": "16",
                  "Species": "LMB",
                  "CatchDate": "2010-02-24T00:00:00",
                  "Trip": "Murray1",
                  "Angler": "Willie",
                  "Quantity": "1",
                  "Weight": "3",
                  "Bait": "one big ass bait",
                  "HookType": "Bait",
                  "LineTest": "10",
                  "Time": "1899-12-30T11:20:00"
               }
            ]
         },
         {
            "ID": "2",
            "Trip": "Murray2",
            "StartDate": "2009-01-20T00:00:00",
            "Duration": "2",
            "Place": "San Vicente",
            "Photos": "F:\\D_Drive\\FishProject\\images\\btn_largemouth_bass.jpg",
            "Notes": "new notes",
            "Anglers": "Willie, Steve",
            "ImgCaption": "okayyyy",
            "CatchTbl": [
               {
                  "ID": "2",
                  "Species": "catfish",
                  "CatchDate": "2009-02-20T00:00:00",
                  "Trip": "Murray2",
                  "Location": "By the drain",
                  "Angler": "Willie",
                  "Quantity": "1",
                  "Weight": "10",
                  "Length": "12",
                  "Girth": "26",
                  "FightTime": "10",
                  "Outcome": "Released",
                  "Style": "Carolina",
                  "Bait": "Roboworm",
                  "BaitColor": "purple",
                  "Notes": "more blah",
                  "AirTemp": "88",
                  "WindDirection": "w",
                  "Wind": "mild",
                  "SkyCondition": "clear",
                  "LunarPhase": "Half",
                  "Pressure": "10",
                  "Barometer": "35",
                  "WaterTemp": "70",
                  "WaterDepth": "12",
                  "WaterPh": "3",
                  "Current": "none",
                  "Bottom": "sand",
                  "WaterColor": "stained",
                  "Tide": "low",
                  "WaterLevel": "low",
                  "Seas": "calm",
                  "Rod": "Quantuum",
                  "Reel": "Quantuum",
                  "HookSize": "2",
                  "HookType": "Bait",
                  "SinkerWeight": "0.5",
                  "SinkerStyle": "Bullet",
                  "LineTest": "12",
                  "LineStyle": "Braid",
                  "LineColor": "Green",
                  "ImgCaption": "new dock at loveland",
                  "Time": "1899-12-30T09:30:00"
               }
            ]
         },
         {
            "ID": "3",
            "Trip": "murray3",
            "StartDate": "2008-02-20T00:00:00",
            "Duration": "1",
            "Place": "Loveland",
            "Photos": "F:\\D_Drive\\FishProject\\images\\bass_bg.jpg",
            "Notes": "more notes",
            "Anglers": "Willie",
            "ImgCaption": "fgfghju",
            "CatchTbl": [
               {
                  "ID": "3",
                  "Species": "LMB",
                  "CatchDate": "2009-01-10T00:00:00",
                  "Trip": "murray3",
                  "Location": "By the drain",
                  "Angler": "Willie",
                  "Quantity": "1",
                  "Weight": "3",
                  "Length": "23",
                  "Girth": "12",
                  "FightTime": "2",
                  "Outcome": "Released",
                  "Style": "Carolina",
                  "Bait": "Frog",
                  "BaitColor": "green",
                  "Notes": "notes",
                  "AirTemp": "55",
                  "WindDirection": "sw",
                  "Wind": "none",
                  "SkyCondition": "clearly",
                  "LunarPhase": "Crescent",
                  "Pressure": "32",
                  "Barometer": "23",
                  "WaterTemp": "56",
                  "WaterDepth": "22",
                  "WaterPh": "1",
                  "Current": "strong",
                  "Bottom": "muddy",
                  "WaterColor": "green",
                  "Tide": "mid",
                  "WaterLevel": "low",
                  "Seas": "flat",
                  "Rod": "Shimano",
                  "Reel": "Shimano",
                  "HookSize": "2",
                  "HookType": "Circle",
                  "SinkerWeight": "4",
                  "SinkerStyle": "Drop Shot",
                  "LineTest": "3",
                  "LineStyle": "Braid",
                  "LineColor": "Green",
                  "ImgCaption": "loveland"
               },
               {
                  "ID": "7",
                  "Species": "shark",
                  "CatchDate": "2008-02-24T00:00:00",
                  "Trip": "murray3",
                  "Location": "by entrance",
                  "Angler": "Willie",
                  "Quantity": "1",
                  "Weight": "3",
                  "Length": "23",
                  "Girth": "38",
                  "FightTime": "10",
                  "Outcome": "lost it",
                  "Style": "kentucky rig",
                  "Bait": "crawdad",
                  "BaitColor": "ox blood",
                  "SkyCondition": "cloudy",
                  "LunarPhase": "waning",
                  "Barometer": "34",
                  "WaterTemp": "65",
                  "WaterDepth": "5",
                  "Rod": "test rod",
                  "Reel": "penn",
                  "HookSize": "4",
                  "HookType": "mosquito",
                  "SinkerWeight": "0",
                  "SinkerStyle": "tungsten",
                  "LineTest": "11",
                  "LineStyle": "spider wire",
                  "LineColor": "blue",
                  "ImgCaption": "big fish"
               }
            ]
         },
         {
            "ID": "4",
            "Trip": "Murray4",
            "StartDate": "2008-02-24T00:00:00",
            "Duration": "1",
            "Place": "El Cap",
            "Photos": "F:\\D_Drive\\FishProject\\images\\activities_largemouth_bass.jpg",
            "Notes": "put notes here...",
            "Anglers": "",
            "CatchTbl": [
               {
                  "ID": "8",
                  "Species": "dorado",
                  "CatchDate": "2009-02-24T00:00:00",
                  "Trip": "Murray4",
                  "Location": "By the drain",
                  "Angler": "Willie",
                  "Quantity": "1",
                  "Weight": "4",
                  "Length": "34",
                  "Girth": "23",
                  "FightTime": "4",
                  "Outcome": "Released",
                  "Style": "Carolina",
                  "Bait": "Shiner",
                  "BaitColor": "White",
                  "SkyCondition": "cloudy",
                  "LunarPhase": "Waxing",
                  "WaterTemp": "34",
                  "WaterDepth": "23",
                  "Rod": "Shimano",
                  "Reel": "Shimano",
                  "HookSize": "4",
                  "HookType": "Bait",
                  "SinkerWeight": "2",
                  "SinkerStyle": "split shot",
                  "LineTest": "10",
                  "LineStyle": "Braid",
                  "LineColor": "Green",
                  "ImgCaption": "large mouth bass",
                  "Time": "1899-12-30T08:27:00"
               },
               {
                  "ID": "12",
                  "Species": "Whale",
                  "CatchDate": "2009-02-10T00:00:00",
                  "Trip": "Murray4",
                  "Location": "Under the tree",
                  "Angler": "testperson",
                  "Quantity": "1",
                  "Weight": "5",
                  "Length": "25",
                  "Girth": "36",
                  "FightTime": "5",
                  "Outcome": "Kept",
                  "Style": "Carolina",
                  "Bait": "Senko",
                  "BaitColor": "Green",
                  "Notes": "i hope this works",
                  "SkyCondition": "cloudy",
                  "LunarPhase": "Waxing",
                  "Barometer": "34",
                  "WaterTemp": "65",
                  "WaterDepth": "20",
                  "Rod": "Quantuum",
                  "Reel": "Shimano",
                  "HookSize": "4",
                  "HookType": "Bait",
                  "SinkerWeight": "1",
                  "SinkerStyle": "Bullet",
                  "LineTest": "10",
                  "LineStyle": "Fluorocarbon",
                  "LineColor": "Clear"
               }
            ]
         },
         {
            "ID": "5",
            "Trip": "chump1",
            "StartDate": "2008-02-24T00:00:00",
            "Duration": "1",
            "Place": "El Cap",
            "Photos": "F:\\D_Drive\\FishProject\\images\\Largemouth.jpg",
            "Notes": "under the tree...",
            "Anglers": "willie willie",
            "ImgCaption": "Skittle",
            "CatchTbl": [
               {
                  "ID": "4",
                  "Species": "LMB",
                  "CatchDate": "2009-02-24T00:00:00",
                  "Trip": "chump1",
                  "Location": "Under the tree",
                  "Angler": "Skittle",
                  "Quantity": "1",
                  "Weight": "6",
                  "Length": "34",
                  "Girth": "34",
                  "FightTime": "5",
                  "Outcome": "Released",
                  "Style": "Carolina",
                  "Bait": "Senko",
                  "BaitColor": "pumpkin",
                  "Pictures": "F:\\D_Drive\\FishProject\\images\\activities_largemouth_bass.jpg",
                  "Notes": "almost got away",
                  "Wind": "strong",
                  "SkyCondition": "cloudy",
                  "LunarPhase": "Crescent",
                  "Barometer": "24",
                  "WaterTemp": "56",
                  "WaterDepth": "76",
                  "Rod": "Shimano",
                  "Reel": "Quantuum",
                  "HookSize": "4",
                  "HookType": "Circle",
                  "SinkerWeight": "5",
                  "SinkerStyle": "Bullet",
                  "LineTest": "10",
                  "LineStyle": "Fluorocarbon",
                  "LineColor": "Clear",
                  "ImgCaption": ""
               },
               {
                  "ID": "112",
                  "Trip": "chump1",
                  "Angler": "Willie",
                  "Quantity": "0",
                  "Weight": "0",
                  "Time": "1899-12-30T18:00:00"
               }
            ]
         },
         {
            "ID": "6",
            "Trip": "murray23",
            "StartDate": "2009-02-24T00:00:00",
            "Duration": "1",
            "Place": "San Vicente",
            "Photos": "F:\\D_Drive\\FishProject\\images\\bass2.jpg",
            "Notes": "notes about murray or san vicente blah",
            "Anglers": "Willie",
            "ImgCaption": "big lake...",
            "CatchTbl": [
               {
                  "ID": "27",
                  "Species": "Pacu",
                  "CatchDate": "2011-10-20T00:00:00",
                  "Trip": "murray23",
                  "Angler": "Willie",
                  "Quantity": "0",
                  "Weight": "0",
                  "Time": "1899-12-30T14:20:00"
               }
            ]
         },
         {
            "ID": "7",
            "Trip": "murray20",
            "StartDate": "2009-02-01T00:00:00",
            "Duration": "1",
            "Place": "El Cap",
            "Notes": "notes about trip tripppp",
            "Anglers": "willie",
            "ImgCaption": "whatever"
         },
         {
            "ID": "9",
            "Trip": "muyrraa334",
            "StartDate": "2009-02-20T00:00:00",
            "Duration": "1",
            "Place": "Loveland",
            "Anglers": "willie",
            "CatchTbl": [
               {
                  "ID": "10",
                  "Species": "LMB",
                  "CatchDate": "2003-02-23T00:00:00",
                  "Trip": "muyrraa334",
                  "Location": "By the drain",
                  "Angler": "Skittle",
                  "Quantity": "1",
                  "Weight": "3",
                  "Length": "23",
                  "Girth": "33",
                  "FightTime": "10",
                  "Outcome": "Kept",
                  "Style": "Carolina",
                  "Bait": "Shiner",
                  "BaitColor": "Shiner",
                  "SkyCondition": "cloudy",
                  "LunarPhase": "Waxing",
                  "WaterTemp": "45",
                  "WaterDepth": "10",
                  "Rod": "Shimano",
                  "Reel": "Quantuum",
                  "HookType": "Circle",
                  "SinkerStyle": "split shot",
                  "LineTest": "10",
                  "LineStyle": "Braid",
                  "LineColor": "Clear"
               }
            ]
         },
         {
            "ID": "10",
            "Trip": "murr3",
            "StartDate": "2004-02-20T00:00:00",
            "Place": "El Cap",
            "CatchTbl": [
               {
                  "ID": "14",
                  "Species": "dorado",
                  "CatchDate": "2009-02-10T00:00:00",
                  "Trip": "murr3",
                  "Location": "Under the tree",
                  "Angler": "testperson",
                  "Quantity": "1",
                  "Weight": "5",
                  "Length": "45",
                  "Girth": "19",
                  "Outcome": "Released",
                  "Style": "Carolina",
                  "Bait": "Senko",
                  "LunarPhase": "Crescent",
                  "HookType": "Circle",
                  "SinkerWeight": "0",
                  "Time": "1899-12-30T10:30:00"
               }
            ]
         },
         {
            "ID": "12",
            "Trip": "chump11",
            "StartDate": "2009-02-21T00:00:00",
            "Duration": "1",
            "Place": "Loveland",
            "Photos": "F:\\D_Drive\\FishProject\\images\\FIL4676.JPG",
            "Notes": "whatever...",
            "Anglers": "me, you",
            "GPS1": "N56.345",
            "GPS2": "W45.234",
            "ImgCaption": "Sal"
         },
         {
            "ID": "13",
            "Trip": "murray05",
            "StartDate": "2009-03-10T00:00:00",
            "Duration": "1",
            "Place": "Lake Murray",
            "Notes": "no specific notes at this time...",
            "Anglers": "Willie",
            "ImgCaption": "tami"
         },
         {
            "ID": "18",
            "Trip": "Murray5",
            "Place": "MCR"
         },
         {
            "ID": "23",
            "Trip": "murray6",
            "StartDate": "2009-02-28T00:00:00",
            "Duration": "1",
            "Place": "Walmart Pond"
         },
         {
            "ID": "24",
            "Trip": "Mcr01",
            "StartDate": "2010-01-20T00:00:00",
            "Duration": "1",
            "Place": "El Cap",
            "Photos": "F:\\D_Drive\\FishProject\\images\\FIL4444.JPG",
            "Anglers": "Willie",
            "ImgCaption": "jiggy",
            "CatchTbl": [
               {
                  "ID": "18",
                  "Species": "LMB",
                  "CatchDate": "2010-01-10T00:00:00",
                  "Trip": "Mcr01",
                  "Location": "under wires",
                  "Angler": "Willie",
                  "Quantity": "1",
                  "Weight": "2",
                  "Outcome": "Released",
                  "Style": "Carolina",
                  "Bait": "crawdad",
                  "LunarPhase": "Crescent",
                  "HookType": "Circle",
                  "LineTest": "10",
                  "Time": "1899-12-30T09:15:00"
               }
            ]
         },
         {
            "ID": "25",
            "Trip": "MCR02",
            "StartDate": "2009-05-06T00:00:00",
            "Duration": "1",
            "Place": "MCR",
            "Anglers": "willie & chris",
            "ImgCaption": "Chris"
         },
         {
            "ID": "27",
            "Trip": "mcr03",
            "Place": "MCR",
            "CatchTbl": [
               {
                  "ID": "20",
                  "Species": "LMB",
                  "CatchDate": "2009-05-06T00:00:00",
                  "Trip": "mcr03",
                  "Location": "under wires",
                  "Angler": "Willie",
                  "Quantity": "1",
                  "Weight": "2",
                  "Length": "23",
                  "Outcome": "Released",
                  "Style": "Carolina",
                  "Bait": "Shiner",
                  "SkyCondition": "clear",
                  "LunarPhase": "Crescent",
                  "Rod": "Crucial",
                  "Reel": "Quantuum",
                  "HookType": "Circle",
                  "LineTest": "10",
                  "ImgCaption": "cold day",
                  "Time": "1899-12-30T06:00:00"
               },
               {
                  "ID": "21",
                  "Species": "LMB",
                  "CatchDate": "2009-05-07T00:00:00",
                  "Trip": "mcr03",
                  "Location": "staples",
                  "Angler": "chris",
                  "Quantity": "1",
                  "Weight": "3",
                  "Outcome": "Released",
                  "Style": "Texas",
                  "Bait": "Shiner",
                  "LunarPhase": "Crescent",
                  "HookType": "Circle",
                  "ImgCaption": "Chris",
                  "Time": "1899-12-30T05:30:00"
               }
            ]
         },
         {
            "ID": "28",
            "Trip": "mcr04",
            "StartDate": "2009-05-07T00:00:00",
            "Duration": "1",
            "Place": "MCR",
            "Anglers": "willie & tami",
            "ImgCaption": "tami",
            "CatchTbl": [
               {
                  "ID": "23",
                  "Species": "LMB",
                  "CatchDate": "2009-05-07T00:00:00",
                  "Trip": "mcr04",
                  "Location": "staples",
                  "Angler": "Willie",
                  "Quantity": "1",
                  "Weight": "4",
                  "Outcome": "Released",
                  "Style": "Texas",
                  "Bait": "Shiner",
                  "LunarPhase": "Crescent",
                  "Rod": "Crucial",
                  "Reel": "Shimano",
                  "HookType": "Circle",
                  "Time": "1899-12-30T10:26:00"
               }
            ]
         },
         {
            "ID": "29",
            "Trip": "Murray10",
            "StartDate": "2009-09-19T00:00:00",
            "Place": "Lake Murray",
            "Anglers": "willie and joe",
            "CatchTbl": [
               {
                  "ID": "25",
                  "Species": "LMB",
                  "CatchDate": "2009-09-19T00:00:00",
                  "Trip": "Murray10",
                  "Location": "toolies",
                  "Angler": "Willie",
                  "Quantity": "1",
                  "Weight": "1",
                  "Outcome": "Released",
                  "Bait": "Senko",
                  "BaitColor": "Pumpkin",
                  "Pictures": "F:\\D_Drive\\FishProject\\images\\FIL2404.JPG",
                  "LunarPhase": "New",
                  "HookType": "Bait",
                  "ImgCaption": "bait"
               }
            ]
         },
         {
            "ID": "30",
            "Trip": "SOMETHING10",
            "StartDate": "2012-04-26T00:00:00",
            "Duration": "3",
            "Place": "Lake Murray",
            "Photos": "F:\\D_Drive\\FishProject\\images\\Largemouth.jpg",
            "Anglers": "all of em",
            "ImgCaption": "well",
            "CatchTbl": [
               {
                  "ID": "29",
                  "Species": "LMB",
                  "Trip": "SOMETHING10",
                  "Location": "under wires",
                  "Angler": "testperson",
                  "Quantity": "1",
                  "Weight": "0",
                  "Outcome": "Released",
                  "Style": "Carolina"
               }
            ]
         },
         {
            "ID": "31",
            "Trip": "lakechump01",
            "StartDate": "2012-07-16T00:00:00",
            "Duration": "1",
            "Place": "Loveland",
            "Notes": "still running tests...",
            "Anglers": "everybody"
         },
         {
            "ID": "32",
            "Trip": "oogabooga",
            "StartDate": "2011-08-31T00:00:00",
            "Duration": "1",
            "Place": "Walmart Pond",
            "Anglers": "me"
         },
         {
            "ID": "33",
            "Trip": "what",
            "Place": "chump lake"
         },
         {
            "ID": "34",
            "Trip": "sowhat",
            "Place": "San Vicente"
         },
         {
            "ID": "35",
            "Trip": "soggy",
            "Place": "Lake Murray"
         },
         {
            "ID": "36",
            "Trip": "dddsseee",
            "Duration": "1",
            "Place": "Loveland"
         },
         {
            "ID": "37",
            "Trip": "okjhgfff",
            "Duration": "1",
            "Place": "Loveland"
         },
         {
            "ID": "38",
            "Trip": "sssssssssssssss",
            "Duration": "1",
            "Place": "Lake Murray"
         },
         {
            "ID": "39",
            "Trip": "sssssssssdeee",
            "Duration": "1",
            "Place": "MCR"
         },
         {
            "ID": "40",
            "Trip": "MurrayFinally",
            "StartDate": "2014-03-17T00:00:00",
            "Duration": "1",
            "Place": "Lake Murray",
            "Notes": "Dave lands a personal record",
            "Anglers": "Willie and Dave",
            "CatchTbl": [
               {
                  "ID": "31",
                  "Species": "LMB",
                  "CatchDate": "2014-03-17T00:00:00",
                  "Trip": "MurrayFinally",
                  "Location": "Under the tree",
                  "Angler": "Dave",
                  "Quantity": "1",
                  "Weight": "5",
                  "Outcome": "Released",
                  "Style": "Drop Shot",
                  "Pictures": "F:\\D_Drive\\FishProject\\images\\dave2.jpg",
                  "ImgCaption": "Daves Record",
                  "Time": "1899-12-30T23:00:00"
               },
               {
                  "ID": "33",
                  "Species": "LMB",
                  "CatchDate": "2014-03-21T00:00:00",
                  "Trip": "MurrayFinally",
                  "Location": "Baseball Field",
                  "Angler": "Dave",
                  "Quantity": "1",
                  "Weight": "3",
                  "Length": "23",
                  "Outcome": "Released",
                  "Style": "Drop Shot",
                  "Bait": "Roboworm",
                  "BaitColor": "Pumpkin",
                  "LunarPhase": "Full",
                  "Rod": "AbuGarcia",
                  "Reel": "Shimano",
                  "Time": "1899-12-30T02:00:00"
               },
               {
                  "ID": "35",
                  "Species": "LMB",
                  "Trip": "MurrayFinally",
                  "Location": "under wires",
                  "Angler": "Willie",
                  "Quantity": "1",
                  "Weight": "10",
                  "Style": "Carolina"
               }
            ]
         },
         {
            "ID": "41",
            "Trip": "MCR Trip 10",
            "StartDate": "2014-03-23T00:00:00",
            "Duration": "1",
            "Place": "MCR",
            "Anglers": "Willie, Dave",
            "CatchTbl": [
               {
                  "ID": "37",
                  "Species": "LMB",
                  "CatchDate": "2014-03-23T00:00:00",
                  "Trip": "MCR Trip 10",
                  "Location": "staples",
                  "Angler": "Dave",
                  "Quantity": "1",
                  "Weight": "1",
                  "Outcome": "Released"
               },
               {
                  "ID": "39",
                  "Species": "LMB",
                  "CatchDate": "2014-03-23T00:00:00",
                  "Trip": "MCR Trip 10",
                  "Location": "staples",
                  "Angler": "Dave",
                  "Quantity": "1",
                  "Weight": "2",
                  "Outcome": "Released"
               },
               {
                  "ID": "41",
                  "Species": "LMB",
                  "CatchDate": "2014-03-23T00:00:00",
                  "Trip": "MCR Trip 10",
                  "Location": "staples",
                  "Angler": "Dave",
                  "Quantity": "1",
                  "Weight": "2",
                  "Outcome": "Released"
               },
               {
                  "ID": "55",
                  "Species": "LMB",
                  "Trip": "MCR Trip 10",
                  "Location": "by entrance",
                  "Angler": "testperson",
                  "Quantity": "1",
                  "Weight": "1",
                  "Outcome": "Released"
               },
               {
                  "ID": "68",
                  "Species": "LMB",
                  "Trip": "MCR Trip 10",
                  "Location": "staples",
                  "Angler": "Willie",
                  "Quantity": "1",
                  "Weight": "2",
                  "Outcome": "Released",
                  "Bait": "Shiner"
               },
               {
                  "ID": "70",
                  "Species": "LMB",
                  "Trip": "MCR Trip 10",
                  "Location": "staples",
                  "Angler": "Willie",
                  "Quantity": "1",
                  "Weight": "2",
                  "Outcome": "Released",
                  "Bait": "Shiner"
               }
            ]
         },
         {
            "ID": "42",
            "Trip": "murraySpawn2014",
            "StartDate": "2014-04-05T00:00:00",
            "Duration": "1",
            "Place": "Lake Murray",
            "Anglers": "Willie and John",
            "CatchTbl": [
               {
                  "ID": "44",
                  "Species": "LMB",
                  "CatchDate": "2014-04-06T00:00:00",
                  "Trip": "murraySpawn2014",
                  "Location": "By the fence",
                  "Angler": "Willie",
                  "Quantity": "1",
                  "Weight": "4",
                  "Outcome": "Released",
                  "Style": "Drop Shot",
                  "Bait": "Roboworm",
                  "BaitColor": "purple",
                  "LunarPhase": "Waxing Crescent",
                  "Rod": "Shimano Crucial",
                  "Reel": "Shimano Sedona",
                  "SinkerStyle": "tungsten",
                  "Time": "1899-12-30T01:00:00"
               },
               {
                  "ID": "46",
                  "Species": "LMB",
                  "CatchDate": "2014-04-06T00:00:00",
                  "Trip": "murraySpawn2014",
                  "Location": "Baseball Field",
                  "Angler": "Willie",
                  "Quantity": "1",
                  "Weight": "2",
                  "Outcome": "Released",
                  "Style": "Drop Shot",
                  "Bait": "Roboworm",
                  "BaitColor": "purple",
                  "LunarPhase": "Waxing Crescent",
                  "Rod": "Shimano Crucial",
                  "Reel": "Shimano Sedona",
                  "SinkerStyle": "tungsten"
               },
               {
                  "ID": "47",
                  "Species": "LMB",
                  "CatchDate": "2014-04-06T00:00:00",
                  "Trip": "murraySpawn2014",
                  "Location": "Baseball Field",
                  "Angler": "John",
                  "Quantity": "1",
                  "Weight": "6",
                  "Outcome": "Released",
                  "Time": "1899-12-30T02:00:00"
               },
               {
                  "ID": "49",
                  "Species": "LMB",
                  "CatchDate": "2014-04-06T00:00:00",
                  "Trip": "murraySpawn2014",
                  "Location": "Baseball Field",
                  "Angler": "John",
                  "Quantity": "1",
                  "Weight": "3",
                  "Outcome": "Released",
                  "Time": "1899-12-30T02:00:00"
               }
            ]
         },
         {
            "ID": "43",
            "Trip": "MurrraySpawn2_2014",
            "StartDate": "2014-04-06T00:00:00",
            "Duration": "1",
            "Place": "Lake Murray",
            "Anglers": "Willie and Dave",
            "CatchTbl": [
               {
                  "ID": "51",
                  "Species": "LMB",
                  "CatchDate": "2014-04-06T00:00:00",
                  "Trip": "MurrraySpawn2_2014",
                  "Location": "Baseball Field",
                  "Angler": "Willie",
                  "Quantity": "1",
                  "Weight": "2",
                  "Outcome": "Released",
                  "Style": "Drop Shot",
                  "Bait": "Roboworm",
                  "BaitColor": "purple",
                  "LunarPhase": "Waxing Crescent",
                  "Rod": "Shimano Claris",
                  "Reel": "Quantuum Spinning",
                  "Time": "1899-12-30T22:00:00"
               },
               {
                  "ID": "52",
                  "Species": "LMB",
                  "CatchDate": "2014-04-06T00:00:00",
                  "Trip": "MurrraySpawn2_2014",
                  "Location": "Baseball Field",
                  "Angler": "Dave",
                  "Quantity": "1",
                  "Weight": "4",
                  "Outcome": "Released",
                  "Style": "Drop Shot",
                  "Time": "1899-12-30T22:00:00"
               },
               {
                  "ID": "53",
                  "Species": "LMB",
                  "CatchDate": "2014-04-06T00:00:00",
                  "Trip": "MurrraySpawn2_2014",
                  "Location": "Baseball Field",
                  "Angler": "Dave",
                  "Quantity": "1",
                  "Weight": "2",
                  "Outcome": "Released",
                  "Time": "1899-12-30T23:00:00"
               }
            ]
         },
         {
            "ID": "44",
            "Trip": "mURRAYsPAWN3_2014",
            "StartDate": "2014-04-09T00:00:00",
            "Duration": "1",
            "Place": "Lake Murray",
            "Anglers": "Willie and Dave",
            "CatchTbl": [
               {
                  "ID": "56",
                  "Species": "LMB",
                  "CatchDate": "2014-04-09T00:00:00",
                  "Trip": "mURRAYsPAWN3_2014",
                  "Location": "By the fence",
                  "Angler": "Willie",
                  "Quantity": "1",
                  "Weight": "2",
                  "Outcome": "Released",
                  "Style": "Drop Shot",
                  "Bait": "Roboworm",
                  "BaitColor": "Green",
                  "LunarPhase": "Waxing Gibbous",
                  "Rod": "Shimano Claris",
                  "Reel": "Quantuum Spinning",
                  "SinkerStyle": "Drop Shot",
                  "Time": "1899-12-30T22:00:00"
               },
               {
                  "ID": "58",
                  "Species": "LMB",
                  "CatchDate": "2014-04-09T00:00:00",
                  "Trip": "mURRAYsPAWN3_2014",
                  "Location": "By the fence",
                  "Angler": "Willie",
                  "Quantity": "1",
                  "Weight": "3",
                  "Outcome": "Released",
                  "Style": "Drop Shot",
                  "Bait": "Roboworm",
                  "BaitColor": "Green",
                  "LunarPhase": "Waxing Gibbous",
                  "Rod": "Shimano Claris",
                  "Reel": "Quantuum Spinning",
                  "SinkerStyle": "Drop Shot",
                  "Time": "1899-12-30T22:30:00"
               },
               {
                  "ID": "60",
                  "Species": "LMB",
                  "CatchDate": "2014-04-09T00:00:00",
                  "Trip": "mURRAYsPAWN3_2014",
                  "Location": "By the fence",
                  "Angler": "Willie",
                  "Quantity": "1",
                  "Weight": "2",
                  "Outcome": "Released",
                  "Style": "Drop Shot",
                  "Bait": "Roboworm",
                  "BaitColor": "Green",
                  "LunarPhase": "Waxing Gibbous",
                  "Rod": "Shimano Claris",
                  "Reel": "Quantuum Spinning",
                  "SinkerStyle": "Drop Shot",
                  "Time": "1899-12-30T23:00:00"
               },
               {
                  "ID": "62",
                  "Species": "LMB",
                  "CatchDate": "2014-04-09T00:00:00",
                  "Trip": "mURRAYsPAWN3_2014",
                  "Location": "By the fence",
                  "Angler": "Willie",
                  "Quantity": "1",
                  "Weight": "2",
                  "Outcome": "Released",
                  "Style": "Drop Shot",
                  "Bait": "Roboworm",
                  "BaitColor": "Green",
                  "LunarPhase": "Waxing Gibbous",
                  "Rod": "Shimano Claris",
                  "Reel": "Quantuum Spinning",
                  "SinkerStyle": "Drop Shot",
                  "Time": "1899-12-30T23:30:00"
               },
               {
                  "ID": "78",
                  "Species": "LMB",
                  "Trip": "mURRAYsPAWN3_2014",
                  "Angler": "Willie",
                  "Quantity": "0",
                  "Weight": "0"
               }
            ]
         },
         {
            "ID": "45",
            "Trip": "MurraySpawn4_2014",
            "StartDate": "2014-04-13T00:00:00",
            "Duration": "1",
            "Place": "Lake Murray",
            "Anglers": "Willie",
            "CatchTbl": [
               {
                  "ID": "80",
                  "Species": "LMB",
                  "CatchDate": "2014-04-13T00:00:00",
                  "Trip": "MurraySpawn4_2014",
                  "Location": "By the fence",
                  "Angler": "Willie",
                  "Quantity": "1",
                  "Weight": "3"
               }
            ]
         },
         {
            "ID": "46",
            "Trip": "MurrayPostSpawn_2014",
            "StartDate": "2014-04-17T00:00:00",
            "Duration": "1",
            "Place": "Lake Murray",
            "Anglers": "Willie and John",
            "CatchTbl": [
               {
                  "ID": "82",
                  "Species": "LMB",
                  "CatchDate": "2014-04-17T00:00:00",
                  "Trip": "MurrayPostSpawn_2014",
                  "Location": "Baseball Field",
                  "Angler": "Willie",
                  "Quantity": "1",
                  "Weight": "4"
               },
               {
                  "ID": "83",
                  "Species": "LMB",
                  "CatchDate": "2014-04-17T00:00:00",
                  "Trip": "MurrayPostSpawn_2014",
                  "Location": "Past Fence",
                  "Angler": "John",
                  "Quantity": "1",
                  "Weight": "7",
                  "Pictures": "F:\\D_Drive\\FishProject\\images\\Jon_01.jpg",
                  "ImgCaption": "7.5 lb Largemouth Bass"
               },
               {
                  "ID": "86",
                  "Trip": "MurrayPostSpawn_2014",
                  "Angler": "Willie",
                  "Quantity": "0",
                  "Weight": "0"
               },
               {
                  "ID": "87",
                  "Trip": "MurrayPostSpawn_2014",
                  "Angler": "Willie",
                  "Quantity": "0",
                  "Weight": "0"
               }
            ]
         },
         {
            "ID": "47",
            "Trip": "MorenaBlvd01",
            "StartDate": "2014-05-18T00:00:00",
            "Duration": "1",
            "Place": "Morena Blvd",
            "Anglers": "Willie and Dave",
            "CatchTbl": [
               {
                  "ID": "88",
                  "Species": "Mullet",
                  "CatchDate": "2014-05-18T00:00:00",
                  "Trip": "MorenaBlvd01",
                  "Location": "Under the tree",
                  "Angler": "Dave",
                  "Quantity": "1",
                  "Weight": "3",
                  "Outcome": "Released"
               }
            ]
         },
         {
            "ID": "48",
            "Trip": "Murray11",
            "StartDate": "2014-05-21T00:00:00",
            "Duration": "1",
            "Place": "Lake Murray",
            "Anglers": "Willie and Dave",
            "CatchTbl": [
               {
                  "ID": "89",
                  "Species": "LMB",
                  "CatchDate": "2014-05-21T00:00:00",
                  "Trip": "Murray11",
                  "Location": "By the fence",
                  "Angler": "Willie",
                  "Quantity": "1",
                  "Weight": "6",
                  "Outcome": "Released",
                  "Style": "Spy Bait",
                  "Bait": "Spy Bait",
                  "BaitColor": "Shad",
                  "Pictures": "F:\\D_Drive\\FishProject\\images\\willie_fish.jpg",
                  "Reel": "Shimano Curado",
                  "LineTest": "10",
                  "LineStyle": "Fluorocarbon",
                  "ImgCaption": "Not a good pic"
               }
            ]
         },
         {
            "ID": "49",
            "Trip": "Murray2014_5",
            "StartDate": "2014-06-06T00:00:00",
            "Duration": "1",
            "Place": "Lake Murray",
            "Anglers": "Willie and Dave",
            "CatchTbl": [
               {
                  "ID": "90",
                  "Species": "Bluegill",
                  "CatchDate": "2014-06-06T00:00:00",
                  "Trip": "Murray2014_5",
                  "Location": "Past Fence",
                  "Angler": "Willie",
                  "Quantity": "1",
                  "Weight": "2",
                  "Outcome": "Released",
                  "Style": "Spy Bait",
                  "Bait": "Spy Bait",
                  "Reel": "Shimano Curado",
                  "LineTest": "10",
                  "LineStyle": "Fluorocarbon"
               },
               {
                  "ID": "91",
                  "Species": "LMB",
                  "CatchDate": "2014-06-06T00:00:00",
                  "Trip": "Murray2014_5",
                  "Location": "Past Fence",
                  "Angler": "Willie",
                  "Quantity": "1",
                  "Weight": "4",
                  "Outcome": "Released",
                  "Style": "Spy Bait",
                  "Bait": "Spy Bait",
                  "BaitColor": "Shad",
                  "Reel": "Shimano Curado",
                  "LineTest": "10",
                  "LineStyle": "Fluorocarbon"
               }
            ]
         },
         {
            "ID": "50",
            "Trip": "Murray2014_6",
            "StartDate": "2014-06-08T00:00:00",
            "Duration": "1",
            "Place": "Lake Murray",
            "Anglers": "Willie",
            "CatchTbl": [
               {
                  "ID": "92",
                  "Species": "LMB",
                  "CatchDate": "2014-06-08T00:00:00",
                  "Trip": "Murray2014_6",
                  "Location": "Del Cerro Bay",
                  "Angler": "Willie",
                  "Quantity": "1",
                  "Weight": "3",
                  "Outcome": "Released",
                  "Style": "Fly Line",
                  "Bait": "Senko",
                  "BaitColor": "Green",
                  "Reel": "Shimano Curado",
                  "LineTest": "10",
                  "LineStyle": "Fluorocarbon"
               }
            ]
         },
         {
            "ID": "51",
            "Trip": "Barrett01",
            "StartDate": "2014-06-15T00:00:00",
            "Duration": "1",
            "Place": "Barrett Lake",
            "Anglers": "Willie, Jon, Pauline",
            "CatchTbl": [
               {
                  "ID": "93",
                  "Species": "LMB",
                  "CatchDate": "2014-06-15T00:00:00",
                  "Trip": "Barrett01",
                  "Location": "by entrance",
                  "Angler": "Willie",
                  "Quantity": "1",
                  "Weight": "2",
                  "Outcome": "Released",
                  "Bait": "Crankbait"
               },
               {
                  "ID": "94",
                  "Species": "LMB",
                  "CatchDate": "2014-06-18T00:00:00",
                  "Trip": "Barrett01",
                  "Location": "by entrance",
                  "Angler": "Willie",
                  "Quantity": "1",
                  "Weight": "2",
                  "Outcome": "Released",
                  "Style": "Fly Line",
                  "Bait": "Crankbait",
                  "Notes": "Daiwa",
                  "SkyCondition": "Cloudy",
                  "Rod": "Quantuum",
                  "Reel": "Shimano Curado",
                  "LineTest": "10",
                  "LineStyle": "Fluorocarbon",
                  "LineColor": "Clear",
                  "Time": "1899-12-30T06:00:00"
               },
               {
                  "ID": "95",
                  "Species": "LMB",
                  "CatchDate": "2014-06-15T00:00:00",
                  "Trip": "Barrett01",
                  "Location": "by entrance",
                  "Angler": "Willie",
                  "Quantity": "1",
                  "Weight": "2",
                  "Outcome": "Released",
                  "Bait": "Crankbait",
                  "Time": "1899-12-30T06:00:00"
               },
               {
                  "ID": "96",
                  "Species": "LMB",
                  "CatchDate": "2014-06-15T00:00:00",
                  "Trip": "Barrett01",
                  "Location": "by entrance",
                  "Angler": "Willie",
                  "Quantity": "1",
                  "Weight": "3",
                  "Outcome": "Released",
                  "Bait": "Crankbait"
               },
               {
                  "ID": "97",
                  "Species": "LMB",
                  "CatchDate": "2014-06-15T00:00:00",
                  "Trip": "Barrett01",
                  "Location": "by entrance",
                  "Angler": "Willie",
                  "Quantity": "1",
                  "Weight": "1",
                  "Outcome": "Released",
                  "Bait": "Crankbait",
                  "Time": "1899-12-30T07:00:00"
               },
               {
                  "ID": "98",
                  "Species": "LMB",
                  "CatchDate": "2014-06-15T00:00:00",
                  "Trip": "Barrett01",
                  "Location": "by entrance",
                  "Angler": "Willie",
                  "Quantity": "1",
                  "Weight": "2",
                  "Outcome": "Released",
                  "Bait": "Crankbait"
               },
               {
                  "ID": "99",
                  "Species": "LMB",
                  "CatchDate": "2014-06-15T00:00:00",
                  "Trip": "Barrett01",
                  "Location": "by entrance",
                  "Angler": "Willie",
                  "Quantity": "1",
                  "Weight": "2",
                  "Outcome": "Released",
                  "Bait": "Crankbait"
               }
            ]
         },
         {
            "ID": "52",
            "Trip": "Murray_2014_07",
            "StartDate": "2014-06-20T00:00:00",
            "Duration": "1",
            "Place": "Lake Murray",
            "Anglers": "Willie, Dave"
         },
         {
            "ID": "53",
            "Trip": "Murray_2014_08",
            "StartDate": "2014-06-21T00:00:00",
            "Duration": "1",
            "Place": "Lake Murray",
            "Anglers": "Willie, Jon"
         },
         {
            "ID": "54",
            "Trip": "Murray_2014_09",
            "StartDate": "2014-06-28T00:00:00",
            "Duration": "1",
            "Place": "Lake Murray",
            "Anglers": "Willie, Jon"
         },
         {
            "ID": "55",
            "Trip": "NewMurray",
            "StartDate": "2016-05-20T00:00:00",
            "Duration": "1",
            "Place": "Lake Murray",
            "Anglers": "Willie",
            "CatchTbl": [
               {
                  "ID": "100",
                  "Species": "LMB",
                  "CatchDate": "2016-05-20T00:00:00",
                  "Trip": "NewMurray",
                  "Location": "Baseball Field",
                  "Angler": "Willie",
                  "Quantity": "1",
                  "Weight": "5",
                  "Outcome": "Released",
                  "Style": "Carolina",
                  "Bait": "Senko",
                  "Rod": "Shimano",
                  "Reel": "Shimano",
                  "LineTest": "10",
                  "LineStyle": "Fluorocarbon"
               },
               {
                  "ID": "101",
                  "Species": "LMB",
                  "Trip": "NewMurray",
                  "Location": "Under the tree",
                  "Angler": "Willie",
                  "Quantity": "0",
                  "Weight": "0"
               },
               {
                  "ID": "102",
                  "Species": "LMB",
                  "CatchDate": "2016-06-20T00:00:00",
                  "Trip": "NewMurray",
                  "Location": "by entrance",
                  "Angler": "Willie",
                  "Quantity": "0",
                  "Weight": "0",
                  "Time": "1899-12-30T01:00:00"
               },
               {
                  "ID": "103",
                  "Species": "LMB",
                  "CatchDate": "2016-06-20T00:00:00",
                  "Trip": "NewMurray",
                  "Location": "By the drain",
                  "Angler": "Willie",
                  "Quantity": "1",
                  "Weight": "0",
                  "Outcome": "Released",
                  "Reel": "Shimano"
               },
               {
                  "ID": "104",
                  "Species": "LMB",
                  "CatchDate": "2016-06-19T00:00:00",
                  "Trip": "NewMurray",
                  "Location": "under wires",
                  "Angler": "Willie",
                  "Quantity": "1",
                  "Weight": "5",
                  "Outcome": "Released",
                  "Style": "Carolina",
                  "LineStyle": "Braid"
               },
               {
                  "ID": "105",
                  "Species": "LMB",
                  "CatchDate": "2016-06-20T00:00:00",
                  "Trip": "NewMurray",
                  "Angler": "Skittle",
                  "Quantity": "0",
                  "Weight": "0"
               },
               {
                  "ID": "106",
                  "Species": "LMB",
                  "CatchDate": "2016-06-20T00:00:00",
                  "Trip": "NewMurray",
                  "Angler": "Willie",
                  "Quantity": "0",
                  "Weight": "0",
                  "Outcome": "Released"
               },
               {
                  "ID": "107",
                  "Species": "LMB",
                  "Trip": "NewMurray",
                  "Angler": "Willie",
                  "Quantity": "0",
                  "Weight": "0",
                  "Time": "1899-12-30T03:00:00"
               },
               {
                  "ID": "108",
                  "Trip": "NewMurray",
                  "Angler": "Willie",
                  "Quantity": "0",
                  "Weight": "0",
                  "Time": "1899-12-30T19:00:00"
               },
               {
                  "ID": "109",
                  "Trip": "NewMurray",
                  "Angler": "Willie",
                  "Quantity": "0",
                  "Weight": "0",
                  "Time": "1899-12-30T19:00:00"
               },
               {
                  "ID": "110",
                  "Trip": "NewMurray",
                  "Angler": "Willie",
                  "Quantity": "0",
                  "Weight": "0",
                  "Time": "1899-12-30T20:00:00"
               },
               {
                  "ID": "111",
                  "Trip": "NewMurray",
                  "Angler": "Willie",
                  "Quantity": "0",
                  "Weight": "0",
                  "Time": "1899-12-30T10:00:00"
               },
               {
                  "ID": "113",
                  "Species": "LMB",
                  "Trip": "NewMurray",
                  "Angler": "Willie",
                  "Quantity": "1",
                  "Weight": "0",
                  "Time": "1899-12-30T20:00:00"
               },
               {
                  "ID": "114",
                  "Species": "LMB",
                  "Trip": "NewMurray",
                  "Angler": "Willie",
                  "Quantity": "1",
                  "Weight": "0",
                  "Outcome": "Released"
               }
            ]
         }
      ],
      "tblLocation": [
         {
            "ID": "1",
            "Place": "Lake Murray"
         },
         {
            "ID": "2",
            "Place": "Loveland"
         },
         {
            "ID": "3",
            "Place": "El Cap"
         },
         {
            "ID": "4",
            "Place": "San Vicente"
         },
         {
            "ID": "5",
            "Place": "chump lake"
         },
         {
            "ID": "6",
            "Place": "lake2"
         },
         {
            "ID": "7",
            "Place": "lake poway"
         },
         {
            "ID": "8",
            "Place": "MCR"
         },
         {
            "ID": "9",
            "Place": "Walmart Pond"
         },
         {
            "ID": "16",
            "Place": "Morena Blvd"
         },
         {
            "ID": "17",
            "Place": "Barrett Lake"
         }
      ]
   