const catchTbl = [
    {
        ID: 1,
        Species: "LMB",
        CatchDate: "2010-04-26T00:00:00",
        Trip: "Murray1",
        Location: "Under wires",
        Angler: "Willie",
        Quantity: 1,
        Weight: 5,
        Length: 24,
        Girth: 26,
        FightTime: 4,
        Outcome: "Released",
        Style: "Texas",
        Bait: "Senko",
        BaitColor: "green",
        Notes: "blah blah",
        AirTemp: 69,
        WindDirection: "s",
        Wind: "strong",
        SkyCondition: "cloudy",
        LunarPhase: "Full",
        Pressure: 34,
        Barometer: 45,
        WaterTemp: 65,
        WaterDepth: 20,
        WaterPh: 2,
        Current: 2,
        Bottom: "rocky",
        WaterColor: "clear",
        Tide: "high",
        WaterLevel: "high",
        Seas: "rough",
        Rod: "Shimano",
        Reel: "Shimano",
        HookSize: 4,
        HookType: "Circle",
        SinkerWeight: 2.25,
        SinkerStyle: "split shot",
        LineTest: 10,
        LineStyle: "Mono",
        LineColor: "Clear",
        ImgCaption: "Chuckawalla Lizard"
    }
]

export default catchTbl;